#ifndef SENNHEISERDESKTOPCLIENT_GAIAV3_EXPORT_H
#define SENNHEISERDESKTOPCLIENT_GAIAV3_EXPORT_H

#include <QtCore/qglobal.h>

#if defined(GAIA_V3_LIBRARY)
#  define GAIA_V3_EXPORT Q_DECL_EXPORT
#else
#  define GAIA_V3_EXPORT Q_DECL_IMPORT
#endif

#endif // SENNHEISERDESKTOPCLIENT_GAIAV3_EXPORT_H
